-- 2026-09-30 · client "Co i jak 3 · projekty": Vlog + Kampanie tabs, Podcasty merged into YouTube, client covers, new order.
-- Generated from src/content/projects.ts (sort = position in PROJECTS × 10).
alter table public.projects drop constraint if exists projects_category_check;
alter table public.projects add constraint projects_category_check check (category in ('video','vlog','youtube','kampanie','podcasty','social','foto','eventy','creative'));
insert into public.projects (slug,title,category,kind_label,image_url,video_url,featured,sort) values
('anna-jurksztowicz-varsovie','Anna Jurksztowicz feat. Chris Schittulli · Varsovie','video','Teledysk','https://img.youtube.com/vi/FB16i1Bzkbc/maxresdefault.jpg','https://www.youtube.com/watch?v=FB16i1Bzkbc',false,10),
('aria-martelle-rollercoaster','Aria Martelle · Rollercoaster','video','Teledysk','https://img.youtube.com/vi/qxRerk_nlbU/maxresdefault.jpg','https://www.youtube.com/watch?v=qxRerk_nlbU',true,20),
('aria-martelle-lewa-prawa','Aria Martelle · Lewa Prawa','video','Teledysk','https://img.youtube.com/vi/-kyeBeWX5os/maxresdefault.jpg','https://www.youtube.com/watch?v=-kyeBeWX5os',false,30),
('aria-martelle-milosc-roztopi-snieg','Aria Martelle · Miłość roztopi śnieg','video','Teledysk','/projects/aria-martelle-milosc-roztopi-snieg.webp','https://www.youtube.com/watch?v=BW0Sz2ROPKw',false,40),
('aria-martelle-chce-cie-miec','Aria Martelle · Chcę Cię mieć','video','Teledysk','/projects/aria-martelle-chce-cie-miec.webp','https://www.youtube.com/watch?v=FyELq6xYVpw',false,50),
('aria-martelle-szkoda-aury','Aria Martelle x Wiktor Martelle · Szkoda Aury','video','Teledysk','/projects/aria-martelle-szkoda-aury.webp','https://www.youtube.com/watch?v=klEyvjtES2Y',false,60),
('aria-martelle-you-decide','Aria Martelle · You Decide','video','Teledysk','/projects/aria-martelle-you-decide.webp','https://www.youtube.com/watch?v=POjBtvIDITg',false,70),
('aria-martelle-alarm','Aria Martelle · Alarm','video','Teledysk','https://img.youtube.com/vi/mkiLlrsZXOY/maxresdefault.jpg','https://www.youtube.com/watch?v=mkiLlrsZXOY',false,80),
('aria-martelle-tancz','Aria Martelle · Tańcz','video','Teledysk','/projects/aria-martelle-tancz.webp','https://www.youtube.com/watch?v=Ee3UTK5oF-4',false,90),
('aria-martelle-zabawa-z-ogniem','Aria Martelle · Zabawa z Ogniem','video','Reżyseria','https://img.youtube.com/vi/j9vdDPhEMUI/maxresdefault.jpg','https://www.youtube.com/watch?v=j9vdDPhEMUI',true,100),
('vlog-szkoda-aury-backstage','Aria Martelle · Backstage teledysku Szkoda Aury','vlog','Vlog / Kulisy teledysku','/projects/vlog-szkoda-aury-backstage.webp','https://www.youtube.com/watch?v=ny59syBjXcA',false,110),
('vlog-chce-cie-miec-backstage','Aria Martelle · Backstage klipu Chcę Cię mieć','vlog','Vlog / Kulisy teledysku','/projects/vlog-chce-cie-miec-backstage.webp','https://www.youtube.com/watch?v=hi_1KbLKbAw',false,120),
('face-off-2-randka-w-ciemno','Face Off 2 · Randka w ciemno','youtube','Produkcja YouTube / Oliwia Puchacz','https://img.youtube.com/vi/5F2Vwkzobq4/maxresdefault.jpg','https://www.youtube.com/watch?v=5F2Vwkzobq4',true,130),
('vlogmas-swiateczne-grzanie','Vlogmas · Świąteczne grzanie','youtube','Produkcja YouTube / Oliwia Puchacz','https://img.youtube.com/vi/c5G9bB4sres/maxresdefault.jpg','https://www.youtube.com/watch?v=c5G9bB4sres',false,140),
('metamorfozy-przyszlosci-helena-deeds','Metamorfozy Przyszłości · Helena Deeds','youtube','Program / SHOWNEWSPL','https://img.youtube.com/vi/Ofu7MDWxnBA/maxresdefault.jpg','https://www.youtube.com/watch?v=Ofu7MDWxnBA',true,150),
('majka-jezowska-vlog-kuba-wojewodzki','Majka Jeżowska Vlog · Kuba Wojewódzki','youtube','Vlog / YouTube','https://img.youtube.com/vi/D6eYgPmuCRU/maxresdefault.jpg','https://www.youtube.com/watch?v=D6eYgPmuCRU',true,160),
('oliwia-puchacz-czyj-to-zawod','Oliwia Puchacz · Dopasuj zawód do osoby','youtube','Produkcja YouTube / Oliwia Puchacz','/projects/oliwia-puchacz-czyj-to-zawod.webp','https://www.youtube.com/watch?v=Vck4hHQs98k',false,170),
('oliwia-puchacz-5-klamcow','Oliwia Puchacz · 5 kłamców vs ja','youtube','Produkcja YouTube / Oliwia Puchacz','/projects/oliwia-puchacz-5-klamcow.webp','https://www.youtube.com/watch?v=tvWxRsfMyPs',false,180),
('oliwia-puchacz-6-klamcow','Oliwia Puchacz · 6 kłamców vs ja','youtube','Produkcja YouTube / Oliwia Puchacz','/projects/oliwia-puchacz-6-klamcow.webp','https://www.youtube.com/watch?v=NThPC-I5ryM',false,190),
('oliwia-puchacz-ranking-influencerek','Oliwia Puchacz · Która influencerka jest najlepsza?','youtube','Produkcja YouTube / Oliwia Puchacz','/projects/oliwia-puchacz-ranking-influencerek.webp','https://www.youtube.com/watch?v=YRsRiboKDIg',false,200),
('oliwia-puchacz-randka-w-ciemno-outfit','Oliwia Puchacz · Randka w ciemno na bazie outfitu','youtube','Produkcja YouTube / Oliwia Puchacz','/projects/oliwia-puchacz-randka-w-ciemno-outfit.webp','https://www.youtube.com/watch?v=gEoXXfJal8I',false,210),
('legendy-showbiznesu-katarzyna-zak','Legendy Showbiznesu · Katarzyna Żak','youtube','Podcast / Złota Scena','https://img.youtube.com/vi/fuy62dsW8LU/maxresdefault.jpg','https://www.youtube.com/watch?v=fuy62dsW8LU',true,220),
('rozmowy-na-plotnie-marzena-rogalska','Rozmowy na płótnie · Marzena Rogalska','youtube','Podcast','https://img.youtube.com/vi/m7xa0BZkQnA/maxresdefault.jpg','https://www.youtube.com/watch?v=m7xa0BZkQnA',true,230),
('anna-puslecka-podcast-adam-ferency','Anna Puślecka Podcast · Adam Ferency','youtube','Rolka / Podcast','https://img.youtube.com/vi/E0DAIhiHDF0/maxresdefault.jpg','https://www.youtube.com/shorts/E0DAIhiHDF0',false,240),
('anna-puslecka-podcast-dzieci','Anna Puślecka Podcast · Nie będę mogła mieć dzieci','youtube','Rolka / Podcast','https://img.youtube.com/vi/0PBhRGidvRA/maxresdefault.jpg','https://www.youtube.com/shorts/0PBhRGidvRA',false,250),
('swiat-gosi-daj-sie-wyczaic','Świat Gosi · Daj się wyczaić','youtube','Produkcja YouTube','https://img.youtube.com/vi/oxgrf_u2O4Y/maxresdefault.jpg','https://www.youtube.com/watch?v=oxgrf_u2O4Y',false,260),
('gosia-w-warszawie','Gosia w Warszawie','youtube','Produkcja YouTube / Świat Gosi','https://img.youtube.com/vi/s92xjCalMEQ/maxresdefault.jpg','https://www.youtube.com/watch?v=s92xjCalMEQ',false,270),
('kampania-c0l_udxirlg','Pan Lektor','kampanie','Kampania / Reels','/projects/kampania-c0l_udxirlg.webp','https://www.instagram.com/reel/C0L_UdxIrLG/',false,280),
('kampania-dcqmdhxjsnv','CoolPack × Aria Martelle','kampanie','Kampania / Reels','/projects/kampania-dcqmdhxjsnv.webp','https://www.instagram.com/reel/DcQmdhxjSnV/',false,290),
('kampania-czevvsjolni','Pan Lektor','kampanie','Kampania / Reels','/projects/kampania-czevvsjolni.webp','https://www.instagram.com/reel/CzEVVsjoLNI/',false,300),
('kampania-ddi1luoikgi','Otodom','kampanie','Kampania / Reels','/projects/kampania-ddi1luoikgi.webp','https://www.instagram.com/reel/Ddi1luOIKGI/',false,310),
('kampania-ddjfjphoiyf','Otodom','kampanie','Kampania / Reels','/projects/kampania-ddjfjphoiyf.webp','https://www.instagram.com/reel/DdJfjphoiYf/',false,320),
('kampania-dalmmsotpgv','Aria Martelle · Wakacyjny camp na Bali','kampanie','Kampania / Reels','/projects/kampania-dalmmsotpgv.webp','https://www.instagram.com/reel/DaLMMSOtpgV/',false,330),
('kampania-dwl4qojsgkx','Mandoria × Aria Martelle','kampanie','Kampania / Reels','/projects/kampania-dwl4qojsgkx.webp','https://www.instagram.com/reel/DWl4QOjsgkX/',false,340),
('kampania-dscbzosjyhy','Aria Martelle','kampanie','Kampania / Reels','/projects/kampania-dscbzosjyhy.webp','https://www.instagram.com/reel/DScbZoSjYhY/',false,350),
('kampania-dkjbvpdi-b8','Mandoria','kampanie','Kampania / Reels','/projects/kampania-dkjbvpdi-b8.webp','https://www.instagram.com/reel/DKjbVpdI-b8/',false,360),
('kampania-zn8mx6vfx','Chupa Chups × Aria Martelle','kampanie','Kampania / TikTok','/projects/kampania-zn8mx6vfx.webp','https://www.tiktok.com/@aria.martelle/video/7537310690424409366',false,370),
('kampania-zn8mxy5tv','Chupa Chups × Aria Martelle · Dzień Lizaka','kampanie','Kampania / TikTok','/projects/kampania-zn8mxy5tv.webp','https://www.tiktok.com/@aria.martelle/video/7529928551349488918',false,380),
('kampania-zn8mxpbea','The Voice Comeback Stage × Orange','kampanie','Kampania / TikTok','/projects/kampania-zn8mxpbea.webp','https://www.tiktok.com/@aria.martelle/video/7555526943999905046',false,390),
('kampania-zn8mxdo8j','Chupa Chups × Aria Martelle · Back to School','kampanie','Kampania / TikTok','/projects/kampania-zn8mxdo8j.webp','https://www.tiktok.com/@aria.martelle/video/7544014907902151958',false,400),
('kampania-zn8mx5taa','Netflix · XO, Kitty','kampanie','Kampania / TikTok','/projects/kampania-zn8mx5taa.webp','https://www.tiktok.com/@netflixpl/video/7466883093870234902',false,410),
('kampania-dljrty3i4dx','Pan Lektor','kampanie','Kampania / Reels','/projects/kampania-dljrty3i4dx.webp','https://www.instagram.com/reel/DLjrty3I4DX/',false,420),
('kampania-ddqsjh6t4w0','Aria Martelle','kampanie','Kampania / Reels','/projects/kampania-ddqsjh6t4w0.webp','https://www.instagram.com/reel/DdqSJh6t4W0/',false,430),
('kampania-drzy01aju05','Empik · Klub Muzyki','kampanie','Kampania / Reels','/projects/kampania-drzy01aju05.webp','https://www.instagram.com/reel/DRzy01AjU05/',false,440),
('reel-c0egrdgoktv','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/C0EGRdGokTV/',false,450),
('reel-dux5rogjblj','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/DUX5roGjBLJ/',false,460),
('reel-ddj6vegogwf','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/DDJ6veGogWf/',false,470),
('reel-dk9yrwtn5jd','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/DK9yRWTN5jd/',false,480),
('reel-c5gncq5mtdn','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/C5GNcq5MTDn/',false,490),
('reel-c4nryuev9m','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/C4NRyuev9M_/',false,500),
('reel-dvqubOycb7q','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/DVqubOYCB7q/',false,510),
('reel-c-nc1izoclz','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/C_nC1IzocLz/',false,520),
('reel-c7gqs9ondgb','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/C7GqS9oNDgb/',false,530),
('reel-csvt-qwioi','Reels · Star Media','social','Reels / Social',null,'https://www.instagram.com/reel/CsVt-QwIOI_/',false,540),
('black-and-gold','Black & Gold','eventy','Event / Fashion / Special Project',null,null,false,550),
('sesja-kampanijna','Sesja kampanijna','foto','Foto / Kampania',null,null,false,560),
('key-visual','Key visual','creative','Creative / Key visual',null,null,false,570)
on conflict (slug) do update set title=excluded.title, category=excluded.category, kind_label=excluded.kind_label, image_url=excluded.image_url, video_url=excluded.video_url, featured=excluded.featured, sort=excluded.sort, published=true;
delete from public.projects where slug not in ('anna-jurksztowicz-varsovie','aria-martelle-rollercoaster','aria-martelle-lewa-prawa','aria-martelle-milosc-roztopi-snieg','aria-martelle-chce-cie-miec','aria-martelle-szkoda-aury','aria-martelle-you-decide','aria-martelle-alarm','aria-martelle-tancz','aria-martelle-zabawa-z-ogniem','vlog-szkoda-aury-backstage','vlog-chce-cie-miec-backstage','face-off-2-randka-w-ciemno','vlogmas-swiateczne-grzanie','metamorfozy-przyszlosci-helena-deeds','majka-jezowska-vlog-kuba-wojewodzki','oliwia-puchacz-czyj-to-zawod','oliwia-puchacz-5-klamcow','oliwia-puchacz-6-klamcow','oliwia-puchacz-ranking-influencerek','oliwia-puchacz-randka-w-ciemno-outfit','legendy-showbiznesu-katarzyna-zak','rozmowy-na-plotnie-marzena-rogalska','anna-puslecka-podcast-adam-ferency','anna-puslecka-podcast-dzieci','swiat-gosi-daj-sie-wyczaic','gosia-w-warszawie','kampania-c0l_udxirlg','kampania-dcqmdhxjsnv','kampania-czevvsjolni','kampania-ddi1luoikgi','kampania-ddjfjphoiyf','kampania-dalmmsotpgv','kampania-dwl4qojsgkx','kampania-dscbzosjyhy','kampania-dkjbvpdi-b8','kampania-zn8mx6vfx','kampania-zn8mxy5tv','kampania-zn8mxpbea','kampania-zn8mxdo8j','kampania-zn8mx5taa','kampania-dljrty3i4dx','kampania-ddqsjh6t4w0','kampania-drzy01aju05','reel-c0egrdgoktv','reel-dux5rogjblj','reel-ddj6vegogwf','reel-dk9yrwtn5jd','reel-c5gncq5mtdn','reel-c4nryuev9m','reel-dvqubOycb7q','reel-c-nc1izoclz','reel-c7gqs9ondgb','reel-csvt-qwioi','black-and-gold','sesja-kampanijna','key-visual');
